import mongoose from "mongoose";
import slugify from "slugify";
import Product from "../models/Product.js";
import Category from "../models/Category.js";

function serializeProduct(product){const item=product?.toObject?product.toObject():product;const price=Number(item.price??item.sellingPrice??0);return {...item,mrp:Number(item.mrp??price),sellingPrice:Number(item.sellingPrice??price),costPrice:Number(item.costPrice??item.purchasePrice??0),discount:Number(item.discount??0),tax:Number(item.tax??0),image:item.image??item.images?.[0]??"",images:Array.isArray(item.images)?item.images.map((x,i)=>typeof x==="string"?{url:x,filename:x.split("/").pop()||`image-${i}`,order:i,isPrimary:i===0}:x):[],inventory:{stock:Number(item.stock??0),minimumStock:Number(item.minimumStock??5),trackInventory:true,continueSelling:false},featured:Boolean(item.featured),trending:Boolean(item.trending),newArrival:Boolean(item.newArrival),status:item.status??(item.isAvailable===false?"archived":"published")};}

function buildProductData(data){const sellingPrice=Number(data.sellingPrice??data.price??0);return {name:data.name,slug:data.slug||slugify(data.name,{lower:true,strict:true}),anime:data.anime,category:data.category,description:data.description,image:data.image||data.images?.[0]?.url||"",images:Array.isArray(data.images)?data.images.map(x=>typeof x==="string"?x:x.url).filter(Boolean):[],sku:data.sku,barcode:data.barcode,supplier:data.supplier,warehouse:data.warehouse,purchasePrice:Number(data.costPrice??data.purchasePrice??0),price:sellingPrice,stock:Number(data.stock??data.inventory?.stock??0),minimumStock:Number(data.minimumStock??data.inventory?.minimumStock??5),mrp:Number(data.mrp??sellingPrice),sellingPrice,costPrice:Number(data.costPrice??data.purchasePrice??0),discount:Number(data.discount??0),tax:Number(data.tax??0),featured:Boolean(data.featured),trending:Boolean(data.trending),newArrival:Boolean(data.newArrival),status:data.status??(data.published===false?"draft":"published"),isAvailable:data.status!=="archived"};}

class ProductService{async getProducts(query){const{search,category,anime,featured,trending,newArrival,status,sort="newest",page=1,limit=12}=query;const filter={};if(search)filter.$or=[{name:{$regex:search,$options:"i"}},{anime:{$regex:search,$options:"i"}}];if(category){if(mongoose.Types.ObjectId.isValid(category))filter.category=category;else{const doc=await Category.findOne({slug:category});if(!doc)return{products:[],total:0,page:Number(page),pages:0};filter.category=doc._id;}}if(anime)filter.anime={$regex:anime.replace(/-/g," "),$options:"i"};if(status)filter.status=status;if(featured!==undefined)filter.featured=featured==="true"||featured===true;if(trending!==undefined)filter.trending=trending==="true"||trending===true;if(newArrival!==undefined)filter.newArrival=newArrival==="true"||newArrival===true;let sortOption={createdAt:-1};switch(sort){case"price-asc":sortOption={price:1};break;case"price-desc":sortOption={price:-1};break;case"rating":sortOption={averageRating:-1,rating:-1};break;case"trending":sortOption={trending:-1,createdAt:-1};break;default:sortOption={createdAt:-1};}const total=await Product.countDocuments(filter);const products=await Product.find(filter).populate("category").sort(sortOption).skip((Number(page)-1)*Number(limit)).limit(Number(limit));return{products:products.map(serializeProduct),total,page:Number(page),pages:Math.ceil(total/Number(limit))};}
async getProductBySlug(slug){const p=await Product.findOne({slug}).populate("category");return p?serializeProduct(p):null;}
async getProductById(id){const p=await Product.findById(id).populate("category");return p?serializeProduct(p):null;}
async create(data){const category=await Category.findById(data.category);if(!category)throw new Error("Category not found.");return serializeProduct(await Product.create(buildProductData(data)));}
async update(id,data){if(data.category){const category=await Category.findById(data.category);if(!category)throw new Error("Category not found.");}const update=buildProductData(data);Object.keys(update).forEach(k=>{if(update[k]===undefined)delete update[k]});const p=await Product.findByIdAndUpdate(id,update,{new:true,runValidators:true}).populate("category");return p?serializeProduct(p):null;}
async delete(id){const p=await Product.findById(id);if(!p)throw new Error("Product not found.");await p.deleteOne();return true;}}
export default new ProductService();
